### PR TITLE
Improvements and fix for #1.

### PR DESCRIPTION
**Pull request by yawboakye**

### CODE REVIEW

**Comment by bradfrost** [comment]
Thanks very much for this, @yawboakye! I don't think I'm going to merge the pull request just because I'm following the convention put forth by Politespace: https://github.com/filamentgroup/politespace 

This would dramatically alter the nature of the script, and I think we're going to be merging labelmask into Politespace. At least that's what I'm hoping @zachleat wants to do!

**Comment by zachleat** [comment]
Hey @yawboakye, this is good stuff! Feel free to open up an issue on the politespace repo and we can discuss some of these changes—namely using a `data-format` instead of grouplength attributes,  and some JS style we use on our projects.

I think we’ll want to use a Custom event system to add the `labelmask` additions as a plugin to the script. Namely, politespace will want to trigger custom events that labelmask can use instead of monkeypatching.

**Comment by bradfrost** [comment]
That's the first time I've ever heard the term "monkeypatching".

On Friday, May 2, 2014, Zach Leatherman notifications@github.com wrote:

> Hey @yawboakye https://github.com/yawboakye, this is good stuff! Feel
> free to open up an issue on the politespace repo and we can discuss some of
> these changes—namely using a data-format instead of grouplength
> attributes, and some JS style we use on our projects.
> 
> I think we’ll want to use a Custom event system to add the labelmaskadditions as a plugin to the script. Namely, politespace will want to
> trigger custom events that labelmask can use instead of monkeypatching.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/bradfrost/labelmask/pull/2#issuecomment-42072076
> .

## 

---

Brad Frost
http://bradfrostweb.com
http://twitter.com/brad_frost

**Comment by yawboakye** [comment]
I confess I never took a look at Politespace before going ahead to add my changes. Really sorry about that. @zachleat Sure, after I take a good look at Politespace. Thanks :smile:

**Pull request closed without merging**
